import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth, UserButton } from '@clerk/react';
import {
	Chart as ChartJS,
	CategoryScale, LinearScale, PointElement, LineElement,
	BarElement, ArcElement, Tooltip, Legend, Filler,
	RadialLinearScale, ScatterController,
} from 'chart.js';
import { Line, Bar, Doughnut, Scatter, Radar } from 'react-chartjs-2';
import { api } from '../lib/api';
import './Dashboard.css';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, BarElement, ArcElement, Tooltip, Legend, Filler, RadialLinearScale, ScatterController);

const ORANGE       = '#ff3c00';
const ORANGE_DIM   = 'rgba(255,60,0,0.12)';
const WHITE_DIM    = 'rgba(255,255,255,0.06)';
const TYPE_COLORS  = ['#ff3c00','#ff6b3d','#ff9a7a','#ffcab7','#cc3000','#992400'];

const chartDefaults = {
	responsive: true, maintainAspectRatio: false,
	plugins: {
		legend: { display: false },
		tooltip: { backgroundColor: '#1a1a1a', titleColor: '#fff', bodyColor: 'rgba(255,255,255,0.6)', borderColor: '#2a2a2a', borderWidth: 1, padding: 10 },
	},
	scales: {
		x: { grid: { color: WHITE_DIM }, ticks: { color: 'rgba(255,255,255,0.25)', font: { size: 11 } }, border: { color: 'transparent' } },
		y: { grid: { color: WHITE_DIM }, ticks: { color: 'rgba(255,255,255,0.25)', font: { size: 11 } }, border: { color: 'transparent' } },
	},
};

const doughnutOpts = {
	responsive: true, maintainAspectRatio: false,
	plugins: {
		legend: { position: 'right', labels: { color: 'rgba(255,255,255,0.45)', font: { size: 12 }, padding: 16, boxWidth: 10 } },
		tooltip: { backgroundColor: '#1a1a1a', titleColor: '#fff', bodyColor: 'rgba(255,255,255,0.6)' },
	},
	cutout: '68%',
};

const NAV = [
	{ id: 'Overview',    icon: '◈' },
	{ id: 'Heart Rate',  icon: '♥' },
	{ id: 'Calories',    icon: '⚡' },
	{ id: 'Steps',       icon: '◎' },
	{ id: 'Sleep',       icon: '◑' },
	{ id: 'AI Analysis', icon: '✦' },
];

function trend(curr, prev) {
	if (!prev || prev === 0) return null;
	const pct = Math.round(((curr - prev) / prev) * 100);
	return { pct: Math.abs(pct), up: pct >= 0, zero: pct === 0 };
}

function TrendBadge({ curr, prev, invert = false }) {
	const t = trend(curr, prev);
	if (!t || t.zero) return null;
	const positive = invert ? !t.up : t.up;
	return (
		<span className={`trend-badge ${positive ? 'up' : 'down'}`}>
			{t.up ? '↑' : '↓'} {t.pct}%
		</span>
	);
}

function analysisToMarkdown(a) {
	if (!a) return '';
	const L = [];
	L.push(`# Fitness AI Analysis`);
	if (a.context) L.push(`\n> ${a.context}`);
	if (a.quality_score) L.push(`\n**Quality score:** ${a.quality_score}/10${a.quality_verdict ? ` — ${a.quality_verdict}` : ''}`);
	if (a.summary) L.push(`\n## Summary\n\n${a.summary}`);
	const raw = a.raw_output || {};
	const metrics = a.metrics || raw.metrics;
	if (metrics?.length) {
		L.push(`\n## Key Metrics\n`);
		metrics.forEach(m => L.push(`- **${m.label}:** ${m.value}${m.unit ? ` ${m.unit}` : ''}${m.change ? ` (${m.change})` : ''}${m.context ? ` — ${m.context}` : ''}`));
	}
	const rows = raw.comparison_rows;
	if (rows?.length) {
		const aL = raw.comparison_a_label || 'A', bL = raw.comparison_b_label || 'B';
		L.push(`\n## Comparison\n\n| Metric | ${aL} | ${bL} | Winner |\n| --- | --- | --- | --- |`);
		rows.forEach(r => L.push(`| ${r.metric} | ${r.value_a} | ${r.value_b} | ${r.winner === 'a' ? aL : r.winner === 'b' ? bL : 'Tie'} |`));
	}
	if (a.findings?.length) {
		L.push(`\n## Findings\n`);
		a.findings.forEach((f, i) => L.push(`${i + 1}. ${f}`));
	}
	if (a.recommendations?.length) {
		L.push(`\n## Recommendations\n`);
		a.recommendations.forEach((r, i) => L.push(`${i + 1}. ${r}`));
	}
	L.push(`\n---\n_Generated by FitnessAI on ${new Date().toLocaleDateString()}_`);
	return L.join('\n');
}

function lineDs(label, values, color = ORANGE) {
	return {
		label, data: values,
		borderColor: color, backgroundColor: `${color}18`,
		borderWidth: 2, pointRadius: 2, pointBackgroundColor: color,
		tension: 0.4, fill: true,
	};
}

export default function Dashboard() {
	const { getToken } = useAuth();
	const navigate = useNavigate();

	const [tab, setTab]         = useState('Overview');
	const [stats, setStats]     = useState(null);
	const [charts, setCharts]   = useState(null);
	const [summary, setSummary] = useState(null);
	const [history, setHistory] = useState([]);
	const [context, setContext] = useState('');
	const [analyzing, setAnalyzing] = useState(false);
	const [selected, setSelected]   = useState(null);
	const [error, setError]     = useState('');
	const [loading, setLoading] = useState(true);
	const [seeding, setSeeding] = useState(false);
	const [sources, setSources] = useState(null);
	const [copied, setCopied]   = useState(false);

	function exportAnalysis() {
		const md = analysisToMarkdown(selected);
		const blob = new Blob([md], { type: 'text/markdown' });
		const url = URL.createObjectURL(blob);
		const link = document.createElement('a');
		link.href = url;
		link.download = `fitness-analysis-${new Date().toISOString().slice(0, 10)}.md`;
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
		URL.revokeObjectURL(url);
	}

	async function copyAnalysis() {
		try {
			await navigator.clipboard.writeText(analysisToMarkdown(selected));
			setCopied(true);
			setTimeout(() => setCopied(false), 1800);
		} catch {
			setError('Copy failed — your browser blocked clipboard access.');
		}
	}

	useEffect(() => { load(); }, []);

	async function load() {
		setLoading(true);
		try {
			const token = await getToken();
			const [me, chartData, hist, sum, src] = await Promise.all([
				api.getMe(token),
				api.getCharts(token),
				api.getHistory(token),
				api.getSummary(token),
				api.getSources(token).catch(() => null),
			]);
			setStats(me);
			setCharts(chartData);
			setHistory(hist.analyses);
			setSummary(sum);
			setSources(src);
		} catch (e) {
			setError(e.message);
		} finally {
			setLoading(false);
		}
	}

	async function runAnalysis() {
		if (!context.trim()) return;
		setAnalyzing(true);
		setError('');
		try {
			const token = await getToken();
			const result = await api.analyze(token, context);
			setHistory(prev => [result, ...prev]);
			setSelected(result);
			setContext('');
		} catch (e) {
			setError(e.message);
		} finally {
			setAnalyzing(false);
		}
	}

	async function handleDemoSeed() {
		setSeeding(true);
		setError('');
		try {
			const token = await getToken();
			await api.demoSeed(token);
			await load();
		} catch (e) {
			setError(e.message);
		} finally {
			setSeeding(false);
		}
	}

	const tw = summary?.this_week;
	const lw = summary?.last_week;
	const rec = summary?.records;
	const hasData = tw && tw.workouts > 0;
	const noData = !loading && !hasData;
	const noChart = !charts || !charts.calories?.labels?.length;

	return (
		<div className='dash'>
			{/* ── Sidebar ── */}
			<aside className='sidebar'>
				<a href='/' className='sidebar-logo'>FitnessAI</a>

				{summary && (
					<div className='streak-badge'>
						<span className='streak-flame'>🔥</span>
						<div>
							<strong>{summary.streak}</strong>
							<span>day streak</span>
						</div>
					</div>
				)}

				<nav className='sidebar-nav'>
					{NAV.map(({ id, icon }) => (
						<button key={id} className={`sidebar-link ${tab === id ? 'active' : ''}`} onClick={() => setTab(id)}>
							<span className='nav-icon'>{icon}</span>{id}
						</button>
					))}
					<div className='sidebar-divider' />
					<button className='sidebar-link' onClick={() => navigate('/routes')}>
						<span className='nav-icon'>⊕</span>Routes
					</button>
					<button className='sidebar-link log-workout-btn' onClick={() => navigate('/log')}>
						+ Log Workout
					</button>
				</nav>

				<div className='sidebar-user'><UserButton /></div>
			</aside>

			{/* ── Main ── */}
			<main className='dash-main'>
				<header className='dash-header'>
					<div>
						<h1>{tab}</h1>
						{tab === 'Overview' && tw && (
							<p className='dash-subtitle'>This week vs last week</p>
						)}
					</div>
					{seeding && <div className='dash-error'>Seeding demo data…</div>}
					{error && <div className='dash-error'>{error}</div>}
				</header>

				{loading && (
					<div className='dash-loading'>
						<div className='skeleton-row'>
							{[1,2,3].map(i => <div key={i} className='skeleton-card' />)}
						</div>
						<div className='skeleton-chart' />
					</div>
				)}

				{!loading && (
					<div className='dash-content'>

						{/* ── OVERVIEW ── */}
						{tab === 'Overview' && (
							<>
								{/* Welcome prompt when empty */}
								{noData && (
									<div className='welcome-card'>
										<h2 className='welcome-title'>Welcome to FitnessAI</h2>
										<p className='welcome-desc'>
											Your data, unified. Connect your platforms or load sample data to see how it works.
										</p>
										<div className='welcome-actions'>
											<button className='hero-btn' onClick={handleDemoSeed} disabled={seeding}>
												{seeding ? 'LOADING…' : '⚡ LOAD SAMPLE DATA'}
											</button>
											<a href='/log' className='hero-btn-ghost' style={{ textDecoration: 'none', display: 'inline-block' }}>
												+ CONNECT A PLATFORM
											</a>
										</div>
										<div className='welcome-sources'>
											<span className='welcome-tag'>Strava</span>
											<span className='welcome-tag'>Fitbit</span>
											<span className='welcome-tag'>Garmin</span>
											<span className='welcome-tag'>Apple Health</span>
											<span className='welcome-tag'>Nike Run Club</span>
											<span className='welcome-tag'>Google Fit</span>
											<span className='welcome-tag'>Manual</span>
										</div>
									</div>
								)}

								{/* Weekly metric cards */}
								{hasData && tw && (
									<div className='week-row'>
										<WeekCard
											label='WORKOUTS'    accent='#ff3c00'
											value={tw.workouts} unit='sessions'
											trend={<TrendBadge curr={tw.workouts} prev={lw?.workouts} />}
										/>
										<WeekCard
											label='DISTANCE'    accent='#22c55e'
											value={tw.distance_km} unit='km'
											trend={<TrendBadge curr={tw.distance_km} prev={lw?.distance_km} />}
										/>
										<WeekCard
											label='CALORIES'    accent='#f59e0b'
											value={tw.calories} unit='kcal'
											trend={<TrendBadge curr={tw.calories} prev={lw?.calories} />}
										/>
										<WeekCard
											label='AVG HR'      accent='#e05555'
											value={tw.avg_hr || '—'} unit={tw.avg_hr ? 'bpm' : ''}
											trend={tw.avg_hr ? <TrendBadge curr={tw.avg_hr} prev={lw?.avg_hr} invert /> : null}
										/>
									</div>
								)}

								{/* Charts */}
								<div className='chart-grid'>
									<div className='chart-card wide'>
										<p className='chart-title'>CALORIES BURNED</p>
										{noChart ? <Empty /> : (
											<div className='chart-wrap'>
												<Line data={{ labels: charts.calories.labels, datasets: [lineDs('Cal', charts.calories.values)] }} options={chartDefaults} />
											</div>
										)}
									</div>
									<div className='chart-card wide'>
										<p className='chart-title'>HEART RATE</p>
										{noChart ? <Empty /> : (
											<div className='chart-wrap'>
												<Line data={{ labels: charts.heart_rate.labels, datasets: [lineDs('BPM', charts.heart_rate.values, '#e05555')] }} options={chartDefaults} />
											</div>
										)}
									</div>
									<div className='chart-card'>
										<p className='chart-title'>WORKOUT TYPES</p>
										{!charts?.workout_types?.labels?.length ? <Empty /> : (
											<div className='chart-wrap'>
												<Doughnut
													data={{ labels: charts.workout_types.labels, datasets: [{ data: charts.workout_types.values, backgroundColor: TYPE_COLORS, borderWidth: 0 }] }}
													options={doughnutOpts}
												/>
											</div>
										)}
									</div>
									<div className='chart-card'>
										<p className='chart-title'>RECENT WORKOUTS</p>
										<div className='recent-list'>
											{!charts?.recent_workouts?.length ? <Empty /> : charts.recent_workouts.map((w, i) => (
												<div className='recent-item' key={i}>
													<div>
														<span className='recent-type'>{w.workout_type || 'Workout'}</span>
														<span className='recent-date'>{w.timestamp?.slice(0, 10)}</span>
														{w.device && <span className='source-badge'>{w.device.replace(/_/g, ' ')}</span>}
													</div>
													<div className='recent-right'>
														<span>{w.duration_minutes ? `${Math.round(w.duration_minutes)}m` : '—'}</span>
														{w.calories_burned ? <span className='dim-val'>{Math.round(w.calories_burned)} kcal</span> : null}
													</div>
												</div>
											))}
										</div>
									</div>
								</div>

								{/* Personal Records */}
								{rec && Object.values(rec).some(Boolean) && (
									<div className='records-section'>
										<p className='section-label'>PERSONAL RECORDS</p>
										<div className='records-grid'>
											{rec.longest_km   && <RecordCard value={rec.longest_km}  unit='km'    label='Longest Run' />}
											{rec.best_pace    && <RecordCard value={rec.best_pace}   unit='/km'   label='Best Pace' />}
											{rec.max_steps    && <RecordCard value={rec.max_steps.toLocaleString()} unit='steps' label='Most Steps (day)' />}
											{rec.max_calories && <RecordCard value={rec.max_calories} unit='kcal' label='Most Calories' />}
											{rec.max_hr       && <RecordCard value={rec.max_hr}       unit='bpm'  label='Peak Heart Rate' />}
										</div>
									</div>
								)}

								{/* Data Sources */}
								{sources && sources.sources?.length > 0 && (
									<div className='sources-section'>
										<p className='section-label'>DATA SOURCES <span className='section-sub'>{sources.total_entries} total entries</span></p>
										<div className='sources-grid'>
											{sources.sources.map(s => (
												<div className='source-card' key={s.name}>
													<span className='source-indicator' />
													<div className='source-info'>
														<span className='source-name'>{s.name.replace(/_/g, ' ')}</span>
														<span className='source-meta'>{s.count.toLocaleString()} readings</span>
														{s.coverage && (
															<div className='coverage-row'>
																{Object.entries(s.coverage).filter(([,v]) => v > 0).map(([type]) => (
																	<span key={type} className='coverage-dot' title={type}>{{
																		heart_rate: '♥', steps: '◎', sleep: '◑',
																		distance: '↗', calories: '⚡', workouts: '▸',
																	}[type] || type}</span>
																))}
															</div>
														)}
													</div>
													{s.count > 0 && (
														<span className='source-pct'>{Math.round(s.count / sources.total_entries * 100)}%</span>
													)}
												</div>
											))}
										</div>
									</div>
								)}
							</>
						)}

						{/* ── HEART RATE ── */}
						{tab === 'Heart Rate' && (
							<div className='chart-grid'>
								<div className='chart-card full'>
									<p className='chart-title'>DAILY AVG HEART RATE (BPM)</p>
									{!charts?.heart_rate?.labels?.length ? <Empty /> : (
										<div className='chart-wrap tall'>
											<Line data={{ labels: charts.heart_rate.labels, datasets: [lineDs('BPM', charts.heart_rate.values, '#e05555')] }} options={chartDefaults} />
										</div>
									)}
								</div>
							</div>
						)}

						{/* ── CALORIES ── */}
						{tab === 'Calories' && (
							<div className='chart-grid'>
								<div className='chart-card full'>
									<p className='chart-title'>CALORIES BURNED PER DAY</p>
									{!charts?.calories?.labels?.length ? <Empty /> : (
										<div className='chart-wrap tall'>
											<Bar data={{ labels: charts.calories.labels, datasets: [{ label: 'Cal', data: charts.calories.values, backgroundColor: ORANGE, borderRadius: 3 }] }} options={chartDefaults} />
										</div>
									)}
								</div>
							</div>
						)}

						{/* ── STEPS ── */}
						{tab === 'Steps' && (
							<div className='chart-grid'>
								<div className='chart-card full'>
									<p className='chart-title'>DAILY STEPS</p>
									{!charts?.steps?.labels?.length ? <Empty /> : (
										<div className='chart-wrap tall'>
											<Bar data={{ labels: charts.steps.labels, datasets: [{ label: 'Steps', data: charts.steps.values, backgroundColor: 'rgba(100,160,255,0.7)', borderRadius: 3 }] }} options={chartDefaults} />
										</div>
									)}
								</div>
							</div>
						)}

						{/* ── SLEEP ── */}
						{tab === 'Sleep' && (
							<div className='chart-grid'>
								<div className='chart-card full'>
									<p className='chart-title'>SLEEP HOURS PER NIGHT</p>
									{!charts?.sleep?.labels?.length ? <Empty /> : (
										<div className='chart-wrap tall'>
											<Line data={{ labels: charts.sleep.labels, datasets: [lineDs('Hrs', charts.sleep.values, '#a78bfa')] }} options={chartDefaults} />
										</div>
									)}
								</div>
							</div>
						)}

						{/* ── AI ANALYSIS ── */}
						{tab === 'AI Analysis' && (
							<div className='analysis-layout'>
								<div className='analysis-left'>
									<div className='analyze-box'>
										<textarea
											className='analyze-input'
											placeholder='Ask anything — "What were my best recovery weeks?" or "How does sleep affect my heart rate?"'
											value={context}
											onChange={e => setContext(e.target.value)}
											rows={4}
										/>
										<button className='analyze-btn' onClick={runAnalysis} disabled={!context.trim() || analyzing}>
											{analyzing ? 'ANALYZING...' : 'RUN ANALYSIS'}
										</button>
									</div>
									<div className='history-list'>
										<p className='chart-title'>PAST ANALYSES</p>
										{history.length === 0 && <p className='dim'>No analyses yet.</p>}
										{history.map((a, i) => (
											<button key={i} className={`history-item ${selected === a ? 'active' : ''}`} onClick={() => setSelected(a)}>
												<span className='history-context'>{a.context}</span>
												<span className='history-date'>{new Date(a.created_at).toLocaleDateString()}</span>
											</button>
										))}
									</div>
								</div>
								<div className='analysis-right'>
									{selected ? (
										<>
											<div className='result-head'>
												<p className='result-question'>"{selected.context}"</p>
												<div className='result-actions'>
													<button className='result-action-btn' onClick={copyAnalysis} title='Copy as Markdown'>
														{copied ? '✓ Copied' : 'Copy'}
													</button>
													<button className='result-action-btn' onClick={exportAnalysis} title='Download as Markdown'>
														↓ Export
													</button>
												</div>
											</div>
											{selected.quality_score && (
												<div className='quality-row'>
													<span className='quality-score' data-score={selected.quality_score}>{selected.quality_score}/10</span>
													{selected.quality_verdict && <span className='quality-verdict'>{selected.quality_verdict}</span>}
												</div>
											)}
											<div className='result-summary'>{selected.summary}</div>

											{/* Metrics output */}
											{selected.output_type === 'metrics' && selected.metrics?.length > 0 && (
												<div className='result-metrics'>
													{selected.metrics.map((m, i) => (
														<div className='result-metric-card' key={i}>
															<span className='rm-value'>{m.value}{m.unit ? <span className='rm-unit'>{m.unit}</span> : null}</span>
															{m.change && <span className={`rm-change ${m.trend === 'up' ? 'up' : m.trend === 'down' ? 'down' : ''}`}>{m.change}</span>}
															<span className='rm-label'>{m.label}</span>
															{m.context && <span className='rm-context'>{m.context}</span>}
														</div>
													))}
												</div>
											)}

											{/* Chart output */}
											{selected.output_type === 'chart' && selected.data_points?.length > 0 && (
												<div className='result-chart-wrap'>
													{selected.chart_title && <p className='chart-title'>{selected.chart_title.toUpperCase()}</p>}
													<div className='chart-wrap'>
														{(selected.chart_type === 'bar' || selected.chart_type === 'funnel' || !selected.chart_type) && (
															<Bar
																data={{ labels: selected.data_points.map(d => d.label), datasets: [{ label: selected.chart_title || 'Value', data: selected.data_points.map(d => d.value), backgroundColor: ORANGE, borderRadius: 3 }] }}
																options={chartDefaults}
															/>
														)}
														{selected.chart_type === 'line' && (
															<Line
																data={{ labels: selected.data_points.map(d => d.label), datasets: [lineDs(selected.chart_title || 'Value', selected.data_points.map(d => d.value))] }}
																options={chartDefaults}
															/>
														)}
														{selected.chart_type === 'pie' && (
															<Doughnut
																data={{ labels: selected.data_points.map(d => d.label), datasets: [{ data: selected.data_points.map(d => d.value), backgroundColor: TYPE_COLORS, borderWidth: 0 }] }}
																options={doughnutOpts}
															/>
														)}
														{selected.chart_type === 'scatter' && (
															<Scatter
																data={{ datasets: [{ label: selected.chart_title || 'Value', data: selected.data_points.map(d => ({ x: d.x_value ?? 0, y: d.value })), backgroundColor: ORANGE }] }}
																options={chartDefaults}
															/>
														)}
														{selected.chart_type === 'radar' && (() => {
															const raw = selected.raw_output || {};
															const hasB = selected.data_points.some(d => d.value2 != null);
															return (
																<Radar
																	data={{
																		labels: selected.data_points.map(d => d.label),
																		datasets: [
																			{ label: selected.chart_title || 'Series A', data: selected.data_points.map(d => d.value), borderColor: ORANGE, backgroundColor: ORANGE_DIM, pointBackgroundColor: ORANGE, borderWidth: 2 },
																			...(hasB ? [{ label: raw.radar_b_label || 'Series B', data: selected.data_points.map(d => d.value2 || 0), borderColor: '#22c55e', backgroundColor: 'rgba(34,197,94,0.10)', pointBackgroundColor: '#22c55e', borderWidth: 2 }] : []),
																		],
																	}}
																	options={{ responsive: true, maintainAspectRatio: false, scales: { r: { grid: { color: 'rgba(255,255,255,0.06)' }, ticks: { color: 'rgba(255,255,255,0.3)', backdropColor: 'transparent', font: { size: 10 } }, pointLabels: { color: 'rgba(255,255,255,0.6)', font: { size: 11 } } } }, plugins: { legend: { display: hasB, labels: { color: 'rgba(255,255,255,0.5)' } }, tooltip: chartDefaults.plugins.tooltip } }}
																/>
															);
														})()}
													</div>
												</div>
											)}

											{/* Table output */}
											{selected.output_type === 'table' && selected.table_headers?.length > 0 && (
												<div className='result-table-wrap'>
													<table className='result-table'>
														<thead><tr>{selected.table_headers.map((h, i) => <th key={i}>{h}</th>)}</tr></thead>
														<tbody>{(selected.table_rows || []).map((row, i) => (
															<tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>
														))}</tbody>
													</table>
												</div>
											)}

											{/* Comparison output */}
											{selected.output_type === 'comparison' && (() => {
												const raw = selected.raw_output || {};
												const rows = raw.comparison_rows || [];
												if (!rows.length) return null;
												const aLabel = raw.comparison_a_label || 'A';
												const bLabel = raw.comparison_b_label || 'B';
												return (
													<div className='result-table-wrap'>
														<table className='result-table'>
															<thead><tr><th>Metric</th><th style={{color: ORANGE}}>{aLabel}</th><th style={{color:'#60a5fa'}}>{bLabel}</th><th>Winner</th></tr></thead>
															<tbody>{rows.map((r, i) => (
																<tr key={i}>
																	<td>{r.metric}</td>
																	<td style={r.winner === 'a' ? {color:'#22c55e', fontWeight:600} : {}}>{r.value_a}</td>
																	<td style={r.winner === 'b' ? {color:'#22c55e', fontWeight:600} : {}}>{r.value_b}</td>
																	<td style={{opacity:0.6}}>{r.winner === 'tie' ? 'Tie' : r.winner === 'a' ? aLabel : r.winner === 'b' ? bLabel : '—'}</td>
																</tr>
															))}</tbody>
														</table>
													</div>
												);
											})()}

											{/* Heatmap output */}
											{selected.output_type === 'heatmap' && (() => {
												const raw = selected.raw_output || {};
												const vals = raw.heatmap_values || [];
												if (!vals.length) return null;
												const flat = vals.flat();
												const minV = Math.min(...flat), maxV = Math.max(...flat);
												const norm = v => maxV === minV ? 0.5 : (v - minV) / (maxV - minV);
												return (
													<div className='result-table-wrap' style={{overflowX:'auto'}}>
														{raw.heatmap_title && <p className='chart-title'>{raw.heatmap_title.toUpperCase()}</p>}
														<table className='result-table'>
															<thead><tr>
																<th />
																{(raw.heatmap_col_labels || []).map((c, i) => <th key={i}>{c}</th>)}
															</tr></thead>
															<tbody>{vals.map((row, ri) => (
																<tr key={ri}>
																	<td style={{opacity:0.6}}>{(raw.heatmap_row_labels || [])[ri] ?? ri}</td>
																	{row.map((val, ci) => {
																		const n = norm(val);
																		return <td key={ci} style={{background:`rgba(255,60,0,${(n*0.8+0.05).toFixed(2)})`,color:n>0.5?'#fff':'rgba(255,255,255,0.5)',textAlign:'center',fontVariantNumeric:'tabular-nums',minWidth:'48px'}}>{typeof val==='number'?val.toFixed(1):val}</td>;
																	})}
																</tr>
															))}</tbody>
														</table>
													</div>
												);
											})()}

											{/* Code output */}
											{selected.output_type === 'code' && (() => {
												const raw = selected.raw_output || {};
												const blocks = raw.code_blocks || [];
												if (!blocks.length) return null;
												return (
													<div className='result-section'>
														{blocks.map((block, i) => (
															<div key={i} style={{marginBottom:'1.25rem'}}>
																<p className='chart-title'>{block.title} <span style={{opacity:0.4,fontSize:'11px',textTransform:'uppercase',letterSpacing:'0.05em'}}>{block.language}</span></p>
																<pre style={{background:'#111',border:'1px solid #2a2a2a',borderRadius:'6px',padding:'1rem',overflowX:'auto',fontSize:'12px',lineHeight:'1.7',color:'rgba(255,255,255,0.85)',margin:0}}><code>{block.code}</code></pre>
															</div>
														))}
													</div>
												);
											})()}

											{selected.key_findings?.length > 0 && (
												<div className='result-section'>
													<h3>KEY FINDINGS</h3>
													<ul>{selected.key_findings.map((f, i) => <li key={i}>{f}</li>)}</ul>
												</div>
											)}
											{selected.recommendations?.length > 0 && (
												<div className='result-section'>
													<h3>RECOMMENDATIONS</h3>
													<ul>{selected.recommendations.map((r, i) => <li key={i}>{r}</li>)}</ul>
												</div>
											)}
										</>
									) : (
										<div className='result-empty'>Select an analysis or run a new one</div>
									)}
								</div>
							</div>
						)}

					</div>
				)}
			</main>
		</div>
	);
}

function WeekCard({ label, value, unit, trend, accent }) {
	return (
		<div className='week-card' style={{ '--accent': accent }}>
			<div className='week-card-top'>
				<span className='week-label'>{label}</span>
				{trend}
			</div>
			<div className='week-value'>
				{value ?? '—'}
				{unit && <span className='week-unit'>{unit}</span>}
			</div>
		</div>
	);
}

function RecordCard({ value, unit, label }) {
	return (
		<div className='record-card'>
			<span className='record-badge'>PR</span>
			<div className='record-value'>{value}<span className='record-unit'>{unit}</span></div>
			<div className='record-label'>{label}</div>
		</div>
	);
}

function Empty() {
	return <p className='dim empty-msg'>No data yet — connect Strava, Fitbit, or Garmin; import from Apple Health, Nike, or Google Fit; or log a workout manually. Every data source makes your analysis stronger.</p>;
}
